services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: jira
    volumes:
      - ./postgresql:/var/lib/postgresql
  admin:
    image: adminer
    restart: always
    depends_on:
      - dev-db
    ports:
      - 8000:8080